# VLP-32C
image_projection:
  ros__parameters:
    laser:
      num_vertical_scans: 32
      num_horizontal_scans: 1800
      vertical_angle_bottom: -25.0          # degrees
      vertical_angle_top: 15.0              # degrees
      sensor_mount_angle: 0.0               # degrees
      ground_scan_index: 15

    image_projection:
      segment_valid_point_num: 5
      segment_valid_line_num: 3
      segment_theta: 60.0                   # decrese this value may improve accuracy

    topics:
      lidarPoints: "/lidar_points"
      fullCloudProjected: "/full_cloud_projected"
      fullCloudInfo: "/full_cloud_info"
      groundCloud: "/ground_cloud"
      segmentedCloud: "/segmented_cloud"
      segmentedCloudPure: "/segmented_cloud_pure"
      segmentedCloudInfo: "/segmented_cloud_info"
      outlierCloud: "/outlier_cloud"

map_optimization:
  ros__parameters:
    mapping:
      enable_loop_closure: true

      surrounding_keyframe_search_radius: 50.0   # key frame that is within n meters from current pose will be considered for scan-to-map optimization (when loop closure disabled)
      surrounding_keyframe_search_num: 50        # submap size (when loop closure enabled)

      history_keyframe_search_radius: 7.0        # key frame that is within n meters from current pose will be considerd for loop closure
      history_keyframe_search_num: 25            # 2n+1 number of history key frames will be fused into a submap for loop closure
      history_keyframe_fitness_score: 0.3        # the smaller the better alignment

      global_map_visualization_search_radius: 500.0 # key frames with in n meters will be visualized

    topics:
      keyPoseOrigin: "/key_pose_origin"
      laserCloudSurround: "/laser_cloud_surround"
      historyCloud: "/history_cloud"
      correctedCloud: "/corrected_cloud"
      recentCloud: "/recent_cloud"
      aftMappedAdjusted: "/aft_mapped_adjusted"
      loopClosureFlag: "/loop_closure_flag"

feature_association:
  ros__parameters:
    laser:
      num_vertical_scans: 32
      num_horizontal_scans: 1800
      scan_period: 0.1                      # seconds

    mapping:
      mapping_frequency_divider: 10

    featureAssociation:
      edge_threshold: 0.1
      surf_threshold: 0.1
      nearest_feature_search_distance: 5.0

    topics:
      laserCloudSharp: "/laser_cloud_sharp"
      laserCloudLessSharp: "/laser_cloud_less_sharp"
      laserCloudFlat: "/laser_cloud_flat"
      laserCloudLessFlat: "/laser_cloud_less_flat"
      laserCloudCornerLast: "/laser_cloud_corner_last"
      laserCloudSurfLast: "/laser_cloud_surf_last"
      outlierCloudLast: "/outlier_cloud_last"
      laserOdometry: "/laser_odom_to_init"

transform_fusion:
  ros__parameters:
    topics:
      laserOdomToInit: "/laser_odom_to_init"
      integratedToInit: "/integrated_to_init"

/**:
  ros__parameters:
    topics:
      aftMappedToInit: "/aft_mapped_to_init"

    frames:
      cameraInit: "camera_init"
      camera: "camera"
      laserOdom: "laser_odom"
      baseLink: "base_link"
      aftMapped: "aft_mapped"
      mapAdjusted: "map_adjusted"
      aftAdjusted: "aft_adjusted"